# Generated by Django 2.1.4 on 2019-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(default='Not Specified By User', max_length=200)),
                ('software_location', models.FileField(upload_to='software/')),
            ],
        ),
    ]
