# Generated by Django 2.1.4 on 2019-02-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_software',
            name='software_name',
            field=models.CharField(max_length=200),
        ),
    ]
