# Generated by Django 2.2a1 on 2019-02-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_temp_windows_db_windows_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=200)),
                ('playbook_content', models.CharField(max_length=99999)),
            ],
        ),
    ]
