# Generated by Django 2.1.4 on 2019-02-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20190207_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_linux_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
            ],
        ),
    ]
