# Generated by Django 2.2a1 on 2019-02-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_playbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_windows_db',
        ),
        migrations.DeleteModel(
            name='windows_software',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='playbook_content',
            field=models.TextField(max_length=99999),
        ),
    ]
